name: Toto

on:
  push:
    branches: [ master ]

jobs:
    helloworld:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah
    helloworld2:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah
            - name: step 2
              run: exit 1
    helloworld3:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah
            - name: step 2
              run: exit 1
    helloworld4:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah
            - name: step 2
              run: exit 1
    helloworld5:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah
            - name: step 2
              run: exit 1
    helloworld6:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah
            - name: step 2
              run: exit 1
    salut:
        needs: helloworld
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah
    salut2:
        needs: helloworld
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah
    salut3:
        needs: salut2
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah
    salut4:
        needs: salut2
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah

    salut5:
        needs: salut4
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah
    salut6:
        needs: [salut4, salut3, helloworld3, helloworld6]
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello world!"
                ls -lah